"""Design review + root-cause analysis via `claude -p`.

Two sections per submission:
  1. Root cause summary (only emitted when bronze < 8/10) — explains what
     tripped the harness, and distinguishes "broken code" from "conformant-API
     violation caused by an ambitious extension" (e.g., silver/gold students
     who changed the `post` CLI signature to require a board argument).
  2. Design review — TA-style assessment of architecture, code cleanliness,
     logic placement, with references to specific files/lines.

The harness runs per-submission. Reviews are generated by shelling out to
`claude -p --model opus` with a prompt that includes the assignment rubric,
the bronze results, and a dump of the student's source code.
"""
from __future__ import annotations

import subprocess
from pathlib import Path

from .runner import CheckResult

# Files we bundle into the review prompt. Everything else (venvs, __pycache__,
# images, compiled artifacts) is skipped.
CODE_GLOBS = ["*.py", "*.md", "README*", "requirements.txt", "pyproject.toml"]
MAX_FILE_BYTES = 40_000        # per file
MAX_TOTAL_BYTES = 180_000      # across all files — keeps prompts well under context limits


def _number_lines(text: str) -> str:
    """Prefix each line with its 1-based line number, right-padded to 4 wide.

    Done so the reviewer model can cite `file.py:LINE` by copying numbers
    it sees directly, rather than counting newlines (which it does poorly).
    """
    lines = text.splitlines()
    width = max(4, len(str(len(lines))))
    return "\n".join(f"{i:>{width}}  {line}" for i, line in enumerate(lines, start=1))


def _collect_source(work: Path) -> tuple[str, list[str]]:
    """Return (concatenated source with file headers + numbered lines, list of paths included)."""
    seen: set[Path] = set()
    for pattern in CODE_GLOBS:
        for p in work.rglob(pattern):
            if "__pycache__" in p.parts or ".venv" in p.parts:
                continue
            seen.add(p)

    chunks: list[str] = []
    included: list[str] = []
    total = 0
    for p in sorted(seen):
        try:
            text = p.read_text(errors="replace")
        except Exception:
            continue
        if len(text) > MAX_FILE_BYTES:
            text = text[:MAX_FILE_BYTES] + f"\n...[{len(text) - MAX_FILE_BYTES} bytes truncated]"
        numbered = _number_lines(text)
        rel = p.relative_to(work)
        block = (
            f"\n===== {rel} =====\n"
            f"(lines are prefixed with line numbers; cite as `{rel}:LINE` exactly as shown)\n"
            f"{numbered}\n"
        )
        if total + len(block) > MAX_TOTAL_BYTES:
            chunks.append(f"\n[remaining files truncated to stay under prompt budget]\n")
            break
        chunks.append(block)
        included.append(str(rel))
        total += len(block)
    return "".join(chunks), included


def _bronze_summary(bronze: list[CheckResult]) -> str:
    lines = []
    for c in bronze:
        glyph = {"pass": "✅", "fail": "❌", "error": "⚠️"}.get(c.status, "?")
        note = c.note or ""
        if len(note) > 400:
            note = note[:400] + "..."
        lines.append(f"- {c.id} {glyph} {c.name}" + (f" — {note}" if note else ""))
    return "\n".join(lines)


def _silver_summary(silver: list[CheckResult]) -> str:
    if not silver:
        return ""
    lines = []
    for c in silver:
        glyph = {"pass": "✅", "fail": "❌", "skip": "⊘",
                 "claim_mismatch": "⚠️", "error": "⚠️"}.get(c.status, "?")
        note = (c.note or "").replace("\n", " ")
        if len(note) > 200:
            note = note[:200] + "..."
        lines.append(f"  {c.id} {glyph} {c.name} → {c.status}" +
                     (f" — {note}" if note else ""))
    return "\n".join(lines)


from harness.config import weights as _weights_cfg


def _build_prompt(
    assignment_id: str,
    handle: str,
    rubric_text: str,
    bronze: list[CheckResult],
    source_dump: str,
    score: int,
    total: int,
    silver: list[CheckResult] | None = None,
) -> str:
    passed = score
    _w = _weights_cfg(assignment_id) or {"bronze": 20, "style": 10, "silver": 10, "gold": 10}
    w_bronze = _w.get("bronze", 20)
    w_style = _w.get("style", 10)
    w_silver = _w.get("silver", 10)
    w_gold = _w.get("gold", 10)
    w_total = w_bronze + w_style + w_silver + w_gold
    need_root_cause = passed < 8
    failed_ids = [c.id for c in bronze if c.status != "pass"]
    bronze_25 = round(passed / total * w_bronze) if total else 0

    root_cause_block = ""
    if need_root_cause:
        root_cause_block = f"""
### Root Cause Summary (bronze {passed}/{total})

For each failing check ({', '.join(failed_ids)}), explain WHY it failed.
Categorize each failure as ONE of:

  (a) **Real bug** — logic error, crash, missing behavior.
  (b) **Harness over-strictness** — the harness made an assumption the
      student was free to violate per the spec. Common case: the spec
      says "decide what migrate does if bbs.db exists — wipe? skip? error?
      document your choice"; a B6 failure because the student seeds a few
      demo users in init_db is NOT a real bug. GIVE CREDIT IN YOUR BRONZE
      SCORE for these.
  (c) **Silver/gold extension collides with bronze API** — e.g., adding a
      `board` positional arg to `post` broke the harness's `post user msg`
      invocation. The harness now auto-retries with a default board, but if
      a check still fails because of extension-related drift, note it.

Format as 2-4 short bullets. Cite files and line numbers.
"""

    silver_block = ""
    if silver:
        silver_block = f"""
### Harness silver findings

The harness ran deterministic probes against the running server. Use these
as ground truth for whether the spec'd silver features are wired:

{_silver_summary(silver)}

**Soft scoring guidance for the {w_silver} silver points (you still decide):**
  - 0 features pass → bottom of the range
  - 1 feature passes → middle of the range
  - 2+ features pass → top of the range (use quality dimensions to refine)
  - `claim_mismatch`: read the student's code. If the feature IS implemented
    and the harness probe was wrong, credit it. Otherwise count as 0 for
    that feature AND mention the over-claim in the review.
  - Creative silver outside the 5 spec'd features: still credit as before;
    the harness can't see those.
"""

    return f"""You are a teaching assistant grading UATX Software Engineering
Assignment {assignment_id.upper()}. You are writing the FINAL end-of-cohort
grading report for student `{handle}`. Output ONLY the markdown sections
described below — no preamble, no closing remarks.

### Assignment rubric reference
{rubric_text}

### Bronze check results (harness says {passed}/{total} passed)
{_bronze_summary(bronze)}
{silver_block}
### Student source code
{source_dump}

=================================================================

## Context you should bring to this review

Students were allowed AI coding agents, so surface-level cleanliness is
NOT evidence of thoughtful design. Your job is to do a serious QA pass:
actually reason about each silver/gold feature's code path, imagine a
user trying to use it, and find bugs that static cleanliness hides.

**Do not mechanically check a fixed list.** Think about what could go
wrong given THIS student's choices. The bullets below are *examples of
the style of bug worth finding* — they are illustrative, not exhaustive.
If the bugs in this submission don't look like any of these, that does
NOT mean the code is clean; keep looking. Flag anything that a thoughtful
TA would want to know about, whether or not it matches a pattern here.

Illustrative examples of the kind of issues worth finding:

- A gold feature called unconditionally from a bronze command that can
  crash (hardware call, network call, hard-coded filesystem path).
- A UI toggle that doesn't actually toggle because of CSS-class / inline-
  style precedence (e.g. Textual `classes="hidden"` paired with a
  `.hidden {{ display: none; }}` rule and no `remove_class` call).
- The same SQL statement implemented multiple times across CLI / TUI /
  web entry points, where schema evolution will force manual parallel
  changes.
- Module-level side effects that fire on every import.
- Interactive-mode argument heuristics that silently misparse based on
  DB state (e.g. "first token is a board if the board already exists").
- Web re-sort that clobbers SQL ordering (pinned posts lose placement).
- Arrow keys that don't actually navigate per-item (only scroll the
  viewport), when a user would expect selection + per-row actions.
- Native aborts (SIGABRT) that bypass `except Exception:` clauses.
- Pull-based scheduling implementations that LOOK like stubs but are
  actually correct if every read query filters by `scheduled_at <= now`.
  Don't flag these as missing functionality.

These are *examples from prior cohorts*, not a test-matrix. Look beyond
them. Think about thread ordering, reply visibility, pagination edge
cases, off-by-one, empty-state handling, concurrent writes, transaction
boundaries, idempotency, error-message clarity, input validation, and
anything else that could trip a real user.

## Treat README claims as claims, not facts

Don't take the student's README at face value. For each feature the
README claims, walk the code path that would exercise it end-to-end and
verify the claim holds. Common failure modes:

- **Façade features.** Endpoints exist, return reasonable shapes, and even
  show up on landing pages — but no path actually populates the data
  they're supposed to expose. A `/boards` table the user can write to
  but no way to ever assign a post to a board is still a façade. Test:
  trace the create-flow for any data that a read-flow exposes.
- **Claimed semantics that don't hold under the chosen design.** A
  README might pitch cursor pagination as "stable under concurrent
  inserts," but if the student's `ORDER BY` is `id ASC` (tail-appending),
  the offset version is *also* stable, so the cursor's advertised benefit
  doesn't actually accrue in this implementation. Note the gap.
- **Validation claims that don't fire.** "Bio is limited to 200 chars" is
  worth nothing if the only path that enforces it is one Pydantic field
  the create-flow doesn't go through.

If you can't tell whether a claim holds without running the server, say
so explicitly rather than asserting it works.

## Don't double-count defects across components

If a defect is mentioned under "Usability & Runtime Issues" or as a
broken/half-wired feature under Silver/Gold, do NOT also deduct for it
under "Code style / decomposition / reuse." Style points are about
layering, duplication, dead code, naming, file organization — not
re-pricing the same bug a second time. Pick the most natural component
to deduct in and leave the others at the score they'd have if that
specific defect didn't exist.

## Scoring out of {w_total}

Compute a SCORE YOU BELIEVE IS CORRECT, not a rote scaling of the harness.

- **Bronze harness ({w_bronze} pts max).** Starting point is {passed}/10 * {w_bronze} =
  {bronze_25}. Adjust UP if the harness docked points for decisions the
  spec explicitly allowed (e.g., "wipe on migrate" vs "skip duplicates",
  or a legitimate init_db seed). Adjust DOWN if a passing bronze check
  actually has a latent bug that the harness missed but a user would hit.
  Show your work in one line.
- **Code style / decomposition / sensible reuse ({w_style} pts).** Good layering,
  no duplication, logic in the right place. Deduct for parallel SQL across
  entry points, monolithic files, dead code, unclear naming.
- **Silver features ({w_silver} pts).** At least TWO silver features correctly
  wired end-to-end (schema + command + README) for full marks. Partial
  credit if one silver feature works and another is half-built.
- **Gold features ({w_gold} pts).** At least TWO gold-level features working
  for full marks. One polished gold feature is ~4-5. Half-built or
  user-visibly broken gold is ~2-3. Something impressive that WORKS END-
  TO-END including UX polish gets 6-7.

=================================================================

OUTPUT FORMAT — emit exactly these sections in this order:
{root_cause_block}
### Design Review

6-10 sentences. Cover: architecture (layering between CLI/data/presentation),
code cleanliness (dedup, spaghetti, dead code), logic placement, specific
strong/weak patterns. Cite `filename.py:LINE`. Don't hedge.

**Line-number rule (applies to ALL sections below, not just Design Review):**
Every source file in this prompt is presented with line numbers prefixed to
each line (`  42  def foo():`). When you cite `file.py:LINE`, the LINE must
match a line number you can SEE in the prompt — copy it from the prefix, do
not estimate. Wrong line numbers undermine the report's credibility with the
student. If you're unsure where something lives, cite a small range
(`main.py:120-135`) rather than a guessed point cite. If you can't find it
at all, drop the cite rather than invent one.

### Silver Features

For EACH silver feature the student claimed (check README + code):
- State the feature.
- Schema change: wired? `file.py:LINE`.
- Command: wired? `file.py:LINE`.
- Does it actually work end-to-end? Any runtime bugs a user would hit?

List 2-5 features. Be concise — one tight paragraph or bullet per feature.

### Gold Features

Same treatment as Silver, with extra attention to latent runtime bugs.
Look for latent bugs the way a thoughtful TA would, using the examples
above for inspiration but not as a fixed checklist.

### Usability & Runtime Issues

What breaks when you actually USE the app? Scan for: features claimed
but not reachable, UI state that doesn't update, error messages that
leak tracebacks, pagination/scrolling gaps, arrow keys that don't do
what a user would expect, commands with footgun parsing.

Be brief — skip this section only if you genuinely found nothing.

### Final Score: XX / {w_total}

| Component | Points | Max | Notes |
|-----------|--------|-----|-------|
| Bronze harness | XX | {w_bronze} | [one-line adjustment explanation if ≠ {bronze_25}] |
| Code style / decomposition / reuse | XX | {w_style} | [one-line rationale] |
| Silver features | XX | {w_silver} | [one-line rationale] |
| Gold features | XX | {w_gold} | [one-line rationale] |
| **Total** | **XX** | **{w_total}** | |

One final sentence naming the dominant factor in the score.
""".strip()


def generate_review(
    assignment_id: str,
    handle: str,
    work: Path,
    bronze: list[CheckResult],
    rubric_path: Path,
    silver: list[CheckResult] | None = None,
    timeout: int = 300,
) -> dict:
    """Generate root-cause + design-review markdown for one submission.

    Returns a dict: {"markdown": str, "included_files": list[str], "error": str|None}
    """
    total = len(bronze)
    passed = sum(1 for c in bronze if c.status == "pass")
    source_dump, included = _collect_source(work)
    rubric_text = rubric_path.read_text() if rubric_path.exists() else "(rubric file not found)"
    prompt = _build_prompt(
        assignment_id, handle, rubric_text, bronze, source_dump, passed, total,
        silver=silver,
    )

    try:
        proc = subprocess.run(
            ["claude", "-p", "--model", "opus"],
            input=prompt,
            capture_output=True,
            text=True,
            timeout=timeout,
        )
    except subprocess.TimeoutExpired:
        return {"markdown": "", "included_files": included, "error": f"claude -p timed out after {timeout}s"}
    except FileNotFoundError:
        return {"markdown": "", "included_files": included, "error": "claude CLI not on PATH"}

    if proc.returncode != 0:
        tail = (proc.stderr or proc.stdout).strip().splitlines()[-5:]
        return {
            "markdown": "",
            "included_files": included,
            "error": f"claude -p exit {proc.returncode}: {' | '.join(tail)}",
        }

    return {
        "markdown": proc.stdout.strip(),
        "included_files": included,
        "error": None,
    }
